export const ADD_NOTE = 'NOTE/ADDNOTE'
export const DELETE_NOTE = 'NOTE/DELETENOTE'
export const SET_TEXT = 'NOTE/SETTEXT'
export const ADD_TAG = 'NOTE/ADDTAG'
export const DELETE_TAG = 'NOTE/DELETETAG'

export const FETCHNOTES = 'NOTE/FETCHNOTES'
export const POSTNOTES = 'NOTE/POSTNOTES'

export const SHOWLOADER = 'APP/SHOW_LOADER'
export const HIDELOADER = 'APP/HIDE_LOADER'

export const REGISTRATION_REQUEST = 'APP/REGISTRATION_REQUEST'
export const REGISTRATION_REQUEST_FAILURE = 'APP/REGISTRATION_REQUEST_FAILURE'
export const REGISTRATION_REQUEST_SUCCESS = 'APP/REGISTRATION_REQUEST_SUCCESS'